# -*- coding: utf-8 -*-
"""GTFS Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y0J7w24_c0ST8qwUxvpyPzBxizmNLJbB
"""

import os
import pathlib as pl
import json

import marimo as mo
import pandas as pd
import numpy as np
import geopandas as gp
import matplotlib
import folium as fl

import gtfs_kit as gk

os.chdir(r'C:\Users\ohenz\Documents\Spring 2026\AI Agents for Engineers\Final Project\Code\GTFS')

DATA = pl.Path(r'C:\Users\ohenz\Documents\Spring 2026\AI Agents for Engineers\Final Project\Code\GTFS').resolve()

print("Done")

import os

current_directory = os.getcwd()
print("Current working directory:", current_directory)

# List feed

gk.list_feed(DATA)

# Read feed and describe

feed = gk.read_feed(DATA, dist_units="m")
feed.describe()

# Trip stats; reuse these for later speed ups


feed_1 = feed.append_dist_to_stop_times()
print(feed_1.stop_times)
feed_1.stop_times.to_csv('Stop Times and Sequences.csv', index=False)

print('csv saved')

# trip_stats = feed.compute_trip_stats()
# print(trip_stats)
#
# stop_times = feed.stop_times.get_stop_times()
# print(stop_times)
#
# trip_stats.to_csv('TripStats.csv',index=False)
#
# print("Done")

# Route time series
# week = feed_1.get_first_week()
# dates = [week[0], week[6]]
# rts = feed_1.compute_route_time_series(dates, freq="12h")
# rts
